name: flutter_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  camera: 0.8.1+3
  provider: ^5.0.0
  loader_overlay: ^2.0.2+1
  path_provider: ^2.0.5
  intl: ^0.17.0
  f_logs:
    git:
      url: git://github.com/draganjovanovic1/Flogs
  cupertino_icons: ^1.0.3
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.3.0
  flutter_better_camera: ^1.0.2+1
  pytorch_mobile: ^0.2.1
  flutter_charts: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  assets:
    - assets/
  uses-material-design: true